<li>
            <div class="p_tu"><img src="[field:picname/]" width="160" height="210"/></div>
            <div class="p_zi">
              <div class="p_ti">[field:title/]</div>
              <div style=" color:#999; margin-bottom:13px; overflow:hidden; ">[field:description function='cn_substr(@me,250)'/]...</div>
              <a href="[field:arcurl/]">查看详情</a> </div>
            <div class="clear"></div>
          </li>