<li> <a href="[field:arcurl/]">
                <div class="n_sj">
                  <p>[field:pubdate function="MyDate('d',@me)"/]</p>
                  <span>[field:pubdate function="MyDate('Y-m',@me)"/]</span></div>
                <div class="n_zi">
                  <div class="n_ti">[field:title/]</div>
                  <div class="n_xx">[field:description function='cn_substr(@me,250)'/]...</div>
                </div>
                <div class="clear"></div>
                </a> </li>