<li class="nLi on">
      <h3><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></h3>
      <div class="sub">
        <div class="nlogo"></div>
        <div style=" width:750px; float:left">
          <div class="e_nav">
            <ul>
            </ul>
          </div>
          <div class="e_nav">
            <ul>
              {dede:channel  typeid ='1'  reid ='1'  type ='son' }
              <li><a href="[field:typelink/]">[field:typename/]</a></li>
              {/dede:channel}
            </ul>
          </div>
          <div class="e_nav">
            <ul>
              {dede:channel  typeid ='7'  reid ='7'  type ='son' }
              <li><a href="[field:typelink/]">[field:typename/]</a></li>
              {/dede:channel}
            </ul>
          </div>
          <div class="e_nav">
            <ul>
              {dede:channel  typeid ='12'  reid ='12'  type ='son' }
              <li><a href="[field:typelink/]">[field:typename/]</a></li>
              {/dede:channel}
            </ul>
          </div>
          <div class="e_nav">
            <ul>
              {dede:channel  typeid ='16'  reid ='16'  type ='son' }
              <li><a href="[field:typelink/]">[field:typename/]</a></li>
              {/dede:channel}
            </ul>
          </div>
          <div class="e_nav">
            <ul>
              {dede:channel  typeid ='21'  reid ='21'  type ='son' }
              <li><a href="[field:typelink/]">[field:typename/]</a></li>
              {/dede:channel}
            </ul>
          </div>
          <div class="clear"></div>
        </div>
        <div class="nguan">
          <div class="n_er"><img src="/skin/img/weixin.png"  width="430" height="430"  /> </div>
          <div class="fl"><img src="/skin/img/nx.png"  /></div>
          <div class="clear"></div>
          <div class="clear"></div>
        </div>
        <div class="clear"></div>
      </div>
    </li>