<?php
$z[0]=Array("field","",40,68);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",70,99);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",367,524);
$z[2][4]['typeid']="1";
$z[2][4]['reid']="1";
$z[2][4]['type']="son";
$z[3]=Array("channel","\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",626,783);
$z[3][4]['typeid']="7";
$z[3][4]['reid']="7";
$z[3][4]['type']="son";
$z[4]=Array("channel","\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",885,1044);
$z[4][4]['typeid']="12";
$z[4][4]['reid']="12";
$z[4][4]['type']="son";
$z[5]=Array("channel","\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",1146,1305);
$z[5][4]['typeid']="16";
$z[5][4]['reid']="16";
$z[5][4]['type']="son";
$z[6]=Array("channel","\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",1407,1566);
$z[6][4]['typeid']="21";
$z[6][4]['reid']="21";
$z[6][4]['type']="son";

?>