<li>
            <div class="n_tu"><img src="[field:picname/]"/></div>
            <div class="n_zi">
              <p style=" font-size:16px; color:#333; margin-bottom:5px; ">[field:title/]<span class="n_sj">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></p>
              <div style="color:#999; height:80px; margin-bottom:15px; overflow:hidden; ">[field:description function='cn_substr(@me,250)'/]...</div>
              <a href="[field:arcurl/]">立即查看</a> </div>
            <div class="clear"></div>
          </li>