<?php
$z[0]=Array("global","",261,282);
$z[0][4]['name']="cfg_qq";
$z[1]=Array("global","",351,372);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("flink","",583,604);
$z[2][4]['row']="4";
$z[3]=Array("type","\r\n        <li><a href=\"[field:typeurl /]\">联系我们</a></li>\r\n        ",786,894);
$z[3][4]['typeid']="25";
$z[4]=Array("global","",1156,1180);
$z[4][4]['name']="cfg_dizhi";
$z[5]=Array("global","",1227,1251);
$z[5][4]['name']="cfg_email";
$z[6]=Array("global","",1298,1324);
$z[6][4]['name']="cfg_dianhua";
$z[7]=Array("global","",1967,1988);
$z[7][4]['name']="cfg_qq";

?>