<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",390,420);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",981,1016);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",1153,1188);
$z[4][4]['filename']="left.htm";
$z[5]=Array("field","",1256,1285);
$z[5][4]['name']="position";
$z[6]=Array("type","<div class=\"nti\">[field:typename /]</div>",1299,1363);
$z[7]=Array("field","",1447,1475);
$z[7][4]['name']="content";
$z[8]=Array("include","",1596,1633);
$z[8][4]['filename']="footer.htm";

?>